// This sets up the required imports and dependencies and creates a blank schema using a Mongoose schema structure
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// This is the actual schema created and will be used for data structures going forward
// userid is an additional field created on top of the _id auto generated by Mongo DB
// This will be used as an easier to follow reference for users using the system
// The other fields are self-explanatory, but it should be noted that the created
// field is used as an automative time/date creation for a new entry and this will
// be displayed in a more user friendly format in the React/HTML front end

const DataSchema = new Schema(
  {
    userid: {type:Number, unique:true},
    email: String,
    givenName: String,
    familyName:String,
    created: { type: String, required: true, default: Date.now }
  },
);

//  This exports the schema created above for use in the system later
module.exports = mongoose.model("Data", DataSchema);
